# Generated by Django 4.2.13 on 2024-07-08 17:43

from django.db import migrations

def add_new_movies(apps, schema_editor):
    # Get the Movie model
    Movie = apps.get_model('movies', 'Movie')
    
    # Create new movie records
    Movie.objects.create(title="Harry Potter",description="Magical Realm", release_date="2003-09-01", votes=8)

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_new_movies),
    ]
